ktor:
    application:
        modules:
            - com.ApplicationKt.module
    deployment:
        port: 8081
jwt:
    issuer: "http://0.0.0.0:8081"
    domain: "http://0.0.0.0:8081"
    audience: "users"
    realm: "ktor sample app"